name: Publish to NPM

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Publish to NPM
        uses: actions/npm-publish@v4
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
